### ISSUE TITLE
Output log levels

### ISSUE THREAD

**Issue by agargiulo** [TheAppgineer/roon-extension-alarm-clock#1]
Is there anyway to turn down the noise when running this?

**Comment by JanKoudijs** [comment]
Hi @agargiulo,
Sorry, I missed your question, I have notifications enabled now :)

There are different ways to reduce noise or even turn it down completely.
The latest update of the Roon API hides the pinging messages by default, you can update to this by getting into the alarm clock directory and issuing the following command:
`npm update`

Alternatively you can hide all messages by redirecting the output.
On Windows: `node . > nul`
on Linux (Mac?): `node . > /dev/null`

To even hide error messages you should append the following to the above line:
`2>&1`

I hope this answers your question.
