### ISSUE TITLE
Group volume control

### ISSUE THREAD

**Issue by mikea** [TheAppgineer/roon-extension-alarm-clock#2]
Would be great if all speakers in the zone would fade in/out. Only the specified one is, the rest turns on abruptly at the latest volume. 

Not sure if this complicated things, but some speakers in the zone have DSP volume (dB) and some have native volume control. 

I want to try to make a PR myself. Would like a discussion first if you don’t mind. 

What would be the best way to approach this? 

Should we extend UI to show all speakers in the zone? Should we allow selection of the zone instead of speaker?

Or maybe there’s a cross-device volume concept in the API?

**Comment by JanKoudijs** [comment]
Never thought about the use case of fade in/out on grouped zones, but I can see why it is not working. Can you tell a bit more about your setup? What speakers do you use, and do you use Roon to combine 2 mono speakers into a stereo pair or something like that?

Volume control in Roon is output based, so after selecting a zone the volume of the primary output is controlled. Implementing fading for grouped zones would take some extra steps:

* Get the zone that belongs to the primary output
* Get all outputs that belong to the zone
* Perform the fade steps for all the separate outputs

The biggest issue is, like you said, that different devices have different volume ranges, some have a range from 0-15, others 0-100, others use dBs. This means that all these scales have to be lined up to make sure that they reach 0 at the same time in case of a fade out. In case of a fade in the user has to set the required volume for each output separately.

This adds quite some complexity and extra settings, I'm not sure this is the way to go. Maybe it should be restricted to same devices, or same volume ranges as that would be much easier. Which makes it even more relevant to know your use case.

**Comment by mikea** [comment]
Jan,

Thanks a lot for taking time to reply.

My main use-case is multi-room audio. Imagine for this example that you have Bedroom speakers (with alarm) and Living Room. Right now, if you listen to the music the night before with Bedroom+Living Room grouped together, then in the morning bedroom will slowly fade in to a defined volume, but Living Room will start blasting immediately at yesterday's party volume.

Ideally I would like to find a setup where I can set volume for each speaker in the group separately.

If this is not possible/feasible, then at least an option to ungroup the speaker at alarm time.

WDYT?

**Comment by JanKoudijs** [comment]
Hi Mikea,

I looked into the grouped zone support in the Roon API and things are looking good :)

Fade in/out on grouped zones is possible but it works a bit different than one might expect. The zone dropdown in the Roon API in practice is an output selector and if playback is started on such an output the other outputs in the grouped zone start playback as well (in line with your report). The good thing is that the volume of the outputs can be controlled independently, and this can be put into use.

Grouped fading can be taken care of by setting individual alarms for the different outputs of the grouped zone, like you would do if the zones were not grouped. The alarms should be set to the same time and use the same fade time. This approach means that there is independent volume control for each output via the separate alarms and that no extra settings have to be added to the UI.

If you try this with the current Alarm Clock release (v0.7.4) it will not work, but the fixing of the issues it has is a work in progress. I also found an issue in the Roon Transport API for which I created a [PR](https://github.com/RoonLabs/node-roon-api-transport/pull/11).

I'll keep you informed about the progress.

**Comment by JanKoudijs** [comment]
Hi @mikea,

After my previous message I continued on integrating grouped zone support in the extension UI. I just released an update (v0.8.0) that should fulfill your request. When setting up an alarm you still select an output (the primary), this should be the output that's most critical in performing the action (e.g. the one that wakes you). If this output is part of a grouped zone and it is a Play alarm you can set individual volume levels for each output in the group. If you ungroup, the alarm remains working but then only for the primary output. If a fade in or fade out is selected for an output that is part of a group then all outputs of the group will fade.

Please give this a try and let me know how it works out.

PS. I changed the tagging of the Docker image, this means that this time you have to uninstall first, then update the Extension Repository to v0.3.14 and then re-install (don't forget to setup the timezone :)).

![multi-zone-alarm-small](https://user-images.githubusercontent.com/26183008/83909785-b519e800-a769-11ea-909e-22ab28b9ada1.png)

**Comment by JanKoudijs** [comment]
Delivered in version 0.8.x
